DROP TABLE IF EXISTS `arbimon2`.`site_log_files`;
DROP TABLE IF EXISTS `arbimon2`.`site_event_log`;
DROP TABLE IF EXISTS `arbimon2`.`site_data_log`;
DROP TABLE IF EXISTS `arbimon2`.`site_data_log_health_types`;
DROP TABLE IF EXISTS `arbimon2`.`site_data_log_plug_types`;
DROP TABLE IF EXISTS `arbimon2`.`site_data_log_tech_types`;
DROP TABLE IF EXISTS `arbimon2`.`site_connection_log`;
DROP TABLE IF EXISTS `arbimon2`.`site_connection_types`;
DROP TABLE IF EXISTS `arbimon2`.`site_aggrs`;
