version: "3.8"
services:
  mysql:
    image: "mariadb:10.4"
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root-secret
      - MYSQL_DATABASE=arbimon2
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin-secret
volumes:
  data-mysql:
